pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub') // uses Jenkins credentials ID
        DOCKER_IMAGE = 'techdecipher/html-docker-site'
    }

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/techdecipher/Projects'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
		    // Show current directory and list files (for debugging)
                    sh 'pwd'
                    sh 'ls -lah'
                    // Build the docker image
                    dockerImage = docker.build("${DOCKER_IMAGE}:latest")
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Run Container (Optional)') {
            steps {
                sh '''
                  docker rm -f html-container || true
                  docker run -d -p 80:80 --name html-container ${DOCKER_IMAGE}:latest
                '''
            }
        }
    }
}

